# Generated by Django 6.0.2 on 2026-04-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(db_index=True, unique=True)),
                ('service_name', models.CharField(max_length=100)),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('common_vulnerability', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Port Service',
                'verbose_name_plural': 'Port Services',
                'ordering': ['port'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, help_text='Target IP, domain, or IP range', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current scan status', max_length=20)),
                ('result', models.TextField(help_text='Raw Nmap output')),
                ('parsed_results', models.JSONField(blank=True, default=dict, help_text='Structured scan results: {hosts: [{ip, ports: [{port, state, service}]}]}')),
                ('open_ports_count', models.IntegerField(default=0, help_text='Number of open ports found')),
                ('closed_ports_count', models.IntegerField(default=0, help_text='Number of closed ports found')),
                ('filtered_ports_count', models.IntegerField(default=0, help_text='Number of filtered ports found')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the scan was initiated')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the scan actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the scan completed', null=True)),
                ('port_range', models.CharField(default='1-1024', help_text='Port range that was scanned', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan failed', null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this scan')),
                ('user', models.ForeignKey(help_text='User who initiated the scan', on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Result',
                'verbose_name_plural': 'Scan Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField(default=0)),
                ('total_open_ports', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
                ('last_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scanresult')),
            ],
            options={
                'verbose_name_plural': 'Scan History',
            },
        ),
        migrations.CreateModel(
            name='UserScanStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField(default=0)),
                ('total_open_ports', models.IntegerField(default=0)),
                ('average_scan_time', models.FloatField(default=0)),
                ('last_scan_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Scan Statistics',
                'verbose_name_plural': 'User Scan Statistics',
            },
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['user', '-created_at'], name='scanner_sca_user_id_31e6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['status'], name='scanner_sca_status_ee58a9_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['target'], name='scanner_sca_target_f2f4a1_idx'),
        ),
    ]
